version: '3.8'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    restart: always
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 1

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: