version: '3.8'

services:
  web:
    volumes:
      - .:/app
      - flask-static:/app/static

    command: flask run --host=0.0.0.0 --port=5000 --reload

    restart: on-failure

volumes:
  flask-static: