name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t vacunto/my-flask-app:latest .

      - name: Push image to Docker Hub
        run: docker push vacunto/my-flask-app:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 4444
          script: |
            cd /home/vacunto/flask_app
            docker compose pull
            docker compose up -d